VIA_ENABLE          = yes
VIAL_ENABLE         = yes
LTO_ENABLE          = yes

RGB_MATRIX_ENABLE   = yes
RGB_MATRIX_DRIVER	= ws2812
OLED_ENABLE         = yes
OLED_DRIVER         = ssd1306
EXTRAKEY_ENABLE     = yes
NKRO_ENABLE			= yes
WPM_ENABLE			= yes
MOUSEKEY_ENABLE     = yes
COMBO_ENABLE        = yes
TAP_DANCE_ENABLE	= yes
QMK_SETTINGS        = yes
CONSOLE_ENABLE		= yes
RGBLIGHT_ENABLE     = no
KEY_OVERRIDE_ENABLE = no
AUDIO_ENABLE		= no
BACKLIGHT_ENABLE	= no

